Rename package to digipolisgent/qa-drupal
digipolisgent/php_package_qa-drupal pull request #8
Opened 2020-10-07 09:12 UTC by zero2one

The namespace of the project has changed but the references are still pointing to the old namespace.

2020-10-07 09:19 UTC, MPParsley approved these changes

2020-10-08 06:36 UTC, matthijs-va requested changes

2020-10-08 06:36 UTC, matthijs-va commented on configs/grumphp-site.yml
> +      config_file: vendor/digipolis/qa-drupal/configs/phpunit-site.xml
`digipolis` => `digipolisgent`

2020-10-08 07:29 UTC, zero2one commented on configs/grumphp-site.yml
> +      config_file: vendor/digipolis/qa-drupal/configs/phpunit-site.xml
Is fixed.

2020-10-08 14:34 UTC, merged